# Generated by Django 4.2.7 on 2026-08-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_mediaupload_options_mediaupload_media_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaupload',
            options={'ordering': ['-uploaded_at']},
        ),
    ]
